services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    # depends_on:
    #   - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - ENABLE_RAG_LOCAL_WEB_FETCH=true
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_URL=${WEBUI_URL}
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${MICROSOFT_CLIENT_TENANT_ID}
      - MICROSOFT_REDIRECT_URI=${WEBUI_URL}/oauth/microsoft/callback
      - OPENID_PROVIDER_URL=https://login.microsoftonline.com/${MICROSOFT_CLIENT_TENANT_ID}/v2.0/.well-known/openid-configuration
      - MICROSOFT_OAUTH_SCOPE=openid email profile offline_access User.Read
      - ENABLE_MICROSOFT_GRAPH_GROUP_CLAIM=true
      - ENABLE_OAUTH_PERSISTENT_CONFIG=true
      - ENABLE_OAUTH_GROUP_MANAGEMENT=true
      - ENABLE_OAUTH_GROUP_CREATION=true
      - OAUTH_GROUP_CLAIM=jobTitle
      - OAUTH_GROUP_DEFAULT_SHARE=members
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
